server:
  address: 127.0.0.1
  port: 8080
  servlet:
    context-path: /

spring:
  #数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://119.23.204.78:3306/panic_buy?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: jsj
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  #redis缓存
  redis:
    database: 0
    host: 119.23.204.78
    port: 6385
    jedis:
      pool:
        #连接池最大连接数
        max-active: 3000
        #连接池中的最大空闲连接
        max-idle: 10
        #连接池中的最小空闲连接
        min-idle: 0
    timeout: 3000

#mybatis
mybatis:
  mapper-locations: classpath:dao/*.xml
  type-aliases-package: com.jsj.entity
