server:
  port: 2333
spring:
  application:
    name: mq-proxy
  kafka:
    # 指定kafka代理地址，可以多个
    bootstrap-servers: 139.9.77.156:9092
    #provider
    producer:
      #生产的topic
      topic: result
      retries: 0
      # 每次批量发送消息的数量
      batch-size: 4096
      buffer-memory: 40960
      linger: 1
    #consumer
    consumer:
      request-topic: request
      response-topic: response
      # 指定默认消费者group id
      group-id: test-consumer-group
      #连接超时
      session-timeout: 20000
      #消费模式
      auto-offset-reset: earliest
      #是否自动提交，如果为true，消费者的offset将在后台周期性的提交;由于需要处理消息业务，所以本项目必须使用消费端手动提交
      enable-auto-commit: false
      #自动提交时间间隔,
      auto-commit-interval: 100
      #消费线程数设置
      concurrency: 5
      #使用消费者组管理时poll()调用之间的最大延迟。
      max-poll-interval-ms: 5000
      #在单次调用poll()中返回的最大记录数。
      max-poll-records: 1
  #redis缓存
  redis:
    database: 0
    host: 119.23.204.78
    port: 6379
    jedis:
      pool:
        #连接池最大连接数
        max-active: 2000
        #连接池中的最大空闲连接
        max-idle: 200
        #连接池中的最小空闲连接
        min-idle: 5
    timeout: 3000
#自定义配置
data:
  redis:
    product_user_list_prefix: 'sec_kill_product_user_list:'
