server:
  port: 1112

eureka:
  server:
    #关闭自我保护
    enable-self-preservation: false
    #无效节点清理间隔
    eviction-interval-timer-in-ms: 1000
  instance:
    hostname: localhost
  client:
    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
    registerWithEureka: false
    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/